### ISSUE TITLE
create a navigation prototype for the application

### ISSUE THREAD

**Issue by isaakwheeler** [MobileApps-Cascadia/campus-guidebook-android#16]
DOD: Navigation model created in figma

**Comment by Bansenauer-Cascadia** [comment]
The "or" here creates to much guess work in understanding what needs to be done. I created a new issue with for the Android option and updated this one for Figma. Feel free to choose whether or not you want to include this issue, but the Android option is a goal for this Sprint

**Comment by isaakwheeler** [comment]
Thank you I will look into it

**Comment by isaakwheeler** [comment]
That issue is more descriptive and I like the changes you made to this issue. Thank you
