### ISSUE TITLE
Add details fragment for Sustainability info

### ISSUE THREAD

**Issue by ghost** [MobileApps-Cascadia/campus-guidebook-android#49]
Dod: Clicking on sustainability card will take you to detailed fragment

**Comment by Bansenauer-Cascadia** [comment]
@isaakwheeler @odjuliarso @haythamodeh - - can you make clearer how this is different than issue #61.
I recommend having only one person assigned to a card. Even if several people provide input, one person is shepherding it through the process. 

You can split the issue into two or just pick up another item
